# Generated by Django 2.1.2 on 2018-11-09 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wouser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Balance',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Sex',
            new_name='sex',
        ),
    ]
