# Generated by Django 2.1.2 on 2018-11-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wouser', '0002_auto_20181109_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(blank=True, default=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, 'man'), (1, 'woman')], default=0),
        ),
    ]
