# Generated by Django 2.1.2 on 2018-11-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wouser', '0003_auto_20181115_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fcm_registration_id',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
