# Generated by Django 2.1.2 on 2018-11-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_auto_20181115_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='icon2',
            field=models.ImageField(default=None, null=True, upload_to='icon2/'),
        ),
    ]
