# Generated by Django 2.1.2 on 2018-11-15 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmatch',
            name='with_far',
        ),
        migrations.AddField(
            model_name='requestmatch',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='requestmatch',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='requestmatch',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='requestmatch',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
