# Generated by Django 2.1.2 on 2018-11-15 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20181115_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='match',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
