# Generated by Django 2.1.2 on 2018-11-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_auto_20181115_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmatch',
            name='skillful',
            field=models.IntegerField(default=0),
        ),
    ]
