# Generated by Django 2.1.2 on 2018-11-17 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sport', '0002_auto_20181115_1926'),
        ('match', '0007_auto_20181116_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluation',
            old_name='comment',
            new_name='comments',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='sport',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.Sport'),
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='target',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='target',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='writer',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='writer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
